### ISSUE TITLE
Hardware bluetooth button support

### ISSUE THREAD

**Issue by rakajack** [Morlunk/Plumble#101]
My bluetooth button emits "com.zello.ptt.down" when pressed and "com.zello.ptt.up" when released, can you add support for catching this intents to Plumble?

**Comment by BuddyButterfly** [comment]
Which bluetooth button do you use? I have tested Rexon BT-28HC and have a prototype to catch the messages of the PTT. Waits to be integrated into Plumble. But there are other things then to do like implementing BT device management for Plumble etc.

**Comment by rakajack** [comment]
I use Coda Button.

Does your button uses intents for communication? Can I see a pull request to test it?

**Comment by rakajack** [comment]
I found, that there is already support for catching broadcast intents: https://github.com/Morlunk/Plumble/wiki/Inter-process-communication

**Comment by BuddyButterfly** [comment]
Hi,
good idea. I will try to test this interface when I'll find the time. Though, it would be nice to have a full fledged bluetooth support in Plumble where one can choose the bluetooth device for input and for output (having, for example a separate bluetooth mic and a separate bluetooth loudspeaker etc.). The problem is that there are very very few apps where you can choose from whatever bluetooth device you connect and which part from it.
